### PR TITLE
[FLINK-20529] Update Dockerfiles for 1.12.0 release

### PR DESCRIPTION
**Pull request by dianfu**

### CODE REVIEW

**Comment by rmetzger** [comment]
Can you push (or open a PR) the `dev-1.12` branch? It should be there for things to be consistent.

I guess this PR should remove the 1.10 files, as this version is not supported anymore.

**Comment by dianfu** [comment]
@rmetzger Have removed 1.10. Sure, I will create the dev-1.12 branch.

**Comment by dianfu** [comment]
PS: Have pushed the dev-1.12 branch.

**Review by rmetzger — APPROVED** [review]
+1 to merge

**Pull request closed without merging**
