### PR TITLE
[FLINK-34746] Switching to the Apache CDN for Dockerfile

### PR DESCRIPTION
**Pull request by MartijnVisser**

### CODE REVIEW

**Comment by hlteoh37** [comment]
@MartijnVisser can we merge this?

**Comment by MartijnVisser** [comment]
@hlteoh37 Done, but I'm not sure if this actually needs to be backported to the other branches. @lincoln-lil do you know?

**Comment by lincoln-lil** [comment]
@MartijnVisser sorry for my late reply here. @hlteoh37 contacted me on slack, and I checked the release process for [flink-docker](https://github.com/apache/flink-docker?tab=readme-ov-file#release-workflow), and it should start with changes on the dev-xx branch, and then sync the updated dockerfiles to the master branch, so now I think it just needs to backport to the dev branches.

**Comment by hlteoh37** [comment]
Appreciate if I could get your review please! @MartijnVisser or @lincoln-lil :)

**Pull request merged**
