### PR TITLE
[hotfix] Quote wget URLs when downloading Flink

### PR DESCRIPTION
**Pull request by rkhachatryan**
The same fix as #70 for master.

### CODE REVIEW

**Comment by rmetzger** [comment]
Just to make sure, in #70, I meant a forward-port to `dev-master` not `master`.

**Comment by zentol** [comment]
Why is this only a problem now?

**Comment by zentol** [comment]
Shall we close this PR?

**Comment by rkhachatryan** [comment]
Yes, closing this PR.

**Pull request closed without merging**
