### PR TITLE
[FLINK-17167] Add HistoryServer option

### PR DESCRIPTION
**Pull request by derjust**
Adds 'historyserver' as option to start the Docker container.
This option uses Flink's `start-historyserver.sh` start script to start a Flink history server.

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for creating this PR @derjust. 

The Flink community is currently discussing how to improve the existing docker images. The effort can be found under [FLIP-111](https://cwiki.apache.org/confluence/display/FLINK/FLIP-111%3A+Docker+image+unification?src=contextnavpagetreemode). Since this ongoing work is related to your changes, it might make sense to add it once the unification work has completed. 

I'm cc'ing also @azagrebin who works on this thread so that he is aware of it.

**Comment by azagrebin** [comment]
Thanks for the PR @derjust 
I created an issue for this: [FLINK-17167](https://issues.apache.org/jira/browse/FLINK-17167).
We look at it asap when we know how we want to refactor the entry point, probably with similar issue for job mode [FLINK-17164](https://issues.apache.org/jira/browse/FLINK-17164).

**Comment by azagrebin** [comment]
@derjust Sorry for late coming back, could you rebase and open your PR against `dev-master`?

**Comment by derjust** [comment]
@azagrebin I rebased this PR to `dev-master` and rebased my commit accordingly.
Please note that I do not have any permissions in JIRA so I can't update [FLINK-17167](https://issues.apache.org/jira/browse/FLINK-17167) - let alone set it into `In Progress`

**Comment by Myasuka** [comment]
@derjust , could you please rebase with current master branch to resolve conflicts.

**Comment by zentol** [comment]
I'll finalize this PR tomorrow.

**Pull request merged**
