### PR TITLE
[FLINK-16260][docker] Add docker images based on Java 11

### PR DESCRIPTION
**Pull request by iemejia**
I have some doubts now that we are back to the Apache Flink repo.
- Do we need an additional Flink committer in place to merge/publish this Patrick? If so maybe it would be a good idea that you and/or i become one.
- Would an intermediary release like this require a vote in the mailing list too?

R: @patricklucas 
CC: @rmetzger  (in case we need a committer blessing)

### CODE REVIEW

**Comment by tillrohrmann** [comment]
Thanks for creating this PR @iemejia. The community has recently started a discussion about unifying the different Docker images. Andrey published [FLIP-111](https://cwiki.apache.org/confluence/display/FLINK/FLIP-111%3A+Docker+image+unification) which contains some proposals how to improve the situation. Since this PR is somewhat related, I would suggest to postpone this work until FLIP-111 has been agreed upon.

**Comment by iemejia** [comment]
Thanks for the info on FLIP-111 I am just catching up on the discussion and will comment on the thread. I have the impression that this update does not conflict with it. What I understood after a quick look is that the idea is to base most images on the docker official one. So probably is better to have this first, or do you see some essential conflict? Any comments @azagrebin @patricklucas ?

Notice also that I asked above some questions about the release process of the images. Me and Patrick have been maintaining the images during the last three years and we could do releases independent from the Flink release cycle to be able to do minor improvements and adjust to upstream docker changes (for example when they changed the base image we depend on). I think we need to define this process, but well I better comment on this in the ML thread.

**Comment by azagrebin** [comment]
Thanks for looking into this @iemejia @tillrohrmann 
I agree with @iemejia that this looks like an independent effort relative to the current state of FLIP-111. I do see any conflicts atm. Nonetheless, I have some questions:
- @patricklucas and @uce mentioned that they wanted to introduce more suggestions for FLIP-111 so we should make sure that this will be in line with them
- I am new to the docker hub release story and not aware about any agreements about multiplying the number of Java versions for the docker hub images and maintaining them. In general, I would expect an ML discussion about this as mentioned in [FLIP-111 discussion](http://mail-archives.apache.org/mod_mbox/flink-dev/202003.mbox/%3CCALKJtOp2UMAp6z2DPVOxEuQ%3DC-ufu1cTQ2GVaz8M_m%3Dwy3Kq0w%40mail.gmail.com%3E). Could it be that having only Java 11 image is just enough?

**Comment by iemejia** [comment]
Java 11 support was requested by users in february in the [previous repo](https://github.com/docker-flink/docker-flink/issues/97) probably motivated by Flink 1.10.0's new support of Java 11, so I proceeded and created a JIRA in the FLINK's repo and asked some committer to assign it to me. Notice that this ticket precedes the (greatly needed) discussions on improvements (unification) you started @azagrebin. 

I will move this and other extra comments to the ML thread on FLIP-111 and hopefully update missing stuff in the proposal. In the meantime maybe we can do a review round, maybe @patricklucas ?

**Comment by iemejia** [comment]
Friendly ping @patricklucas or can someone else take a look?

**Comment by iemejia** [comment]
Updated PR because it needed a rebase, I also separated into two commits one for the script changes and one for the generated files.

**Comment by iemejia** [comment]
I switched OS in the last week and just noticed that I don't have the image that we used to generate the official-image release, so I filled https://issues.apache.org/jira/browse/FLINK-17324 to tackle this. @patricklucas can you help with it?

**Comment by patricklucas** [comment]
Sorry for not getting to this sooner.

The results look good. I continue to rue the complexity of the bash scripts, especially the stackbrew library one—maybe I'll follow through on my threat of rewriting it in Python at some point.

I verified that the resulting library manifest only adds new tags, and that the Java 8 image is preferred. I of course would also be happy to have only Java 11 images—or at least, making the Java 11 images be the default-tagged starting with Flink 1.11—but I'm not sure the community is ready for that yet.

A discussion/call for reviews on the mailing list seems appropriate, but I'm not sure if this is the sort of thing that requires a vote, since it is only a packaging change, and not a Flink "upstream" source change.

Regarding the build helper Docker image, I replied on the FLINK ticket about it. I think actually the best option would be to have some tooling that runs a vanilla Alpine or Debian container, downloads the bashbrew library from [here](https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/) (as suggested by the bashbrew README), and then runs the script, avoiding a requirement on any prebuilt image.

**Comment by KeatsPeeks** [comment]
Any update on this one ?

**Comment by rmetzger** [comment]
@iemejia any chance you can finish this in the next one or two weeks? Flink 1.11 is around the corner, and it would be nice to have Java 11 images ready at that occasion.

**Comment by basanthjenuhb** [comment]
Any update on this one ? We are waiting to use this for our next project.

**Comment by iemejia** [comment]
Hi @rmetzger I will take a look and hopefully update the PR and ping you back. I just noticed many things changed since I opened this one. I will take a look and comment later on.

**Comment by rmetzger** [comment]
Thanks a lot!

**Comment by hridyeshpant** [comment]
Any update on this @iemejia @tillrohrmann . We are not able to deploy our application which is complied with java 11 
```has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by rmetzger** [comment]
@zentol mentioned to me offline that he might want to revisit how we are maintaining Flink's docker images. What's your opinion how to proceed with this PR Chesnay?

**Comment by cracker2709** [comment]
Still no update?
We are still deploying with jdk 1.8 and are looking forward to deploy it with 11 version.
Thank you

**Comment by pedro93** [comment]
Is there anything that can be done to push this forward? Currently blocked from using flink because it does not have java 11 support.
Thank you for reading.

**Comment by rmetzger** [comment]
@pedro93 Flink does have Java 11 support. But we are not providing any official docker images for Java11 yet. However, it should be fairly easy to build something yourself.
The reason this is so complicated here is that we want to nicely integrate this into our image build workflow, and we want to publish it as an official Flink docker image.

**Comment by rmetzger** [comment]
I guess your Flink instance (JobManager, TaskManagers) are running on a Java8 JVM? It should work if you run your code on a JRE11.

**Comment by iemejia** [comment]
Closing this in favor of a refactored and hopefully more maintainable approach as discussed in the FLINK-16260 ticket.

**Comment by rmetzger** [comment]
For everybody who's subscribed to this PR: we now have Java11 images released

**Comment by lintong** [comment]
That's possibly a dead link: Here are the tag references: https://hub.docker.com/_/flink?tab=tags&page=1&name=java11

**Comment by rmetzger** [comment]
Thanks :)

**Pull request closed without merging**
