### PR TITLE
[FLINK-15978] Add GPG key and Dockerfiles for 1.10.0 release

### PR DESCRIPTION
**Pull request by carp84**
Add GPG key and Dockerfiles for Flink 1.10.0 release

### CODE REVIEW

**Comment by carp84** [comment]
Note: we need to hold the merging until the vote of release candidate has passed. Thanks.

**Comment by carp84** [comment]
The vote of 1.10.0 RC3 is already passed, so we're ready to go here.

@uce @rmetzger could you help review here? Thanks.

**Comment by carp84** [comment]
Thanks for the review @rmetzger @patricklucas !

Will wait for 1.10 binaries available and verify locally before merging. Thanks for the carefully check @rmetzger !

**Comment by carp84** [comment]
Checked and confirmed the 1.10 binaries have been synced to all close mirrors on my site, and I've successfully built an image locally:

```
$ docker build -t flink-1-10-pr-test .
Sending build context to Docker daemon  11.26kB
Step 1/16 : FROM openjdk:8-jre
 ---> 2df355aab4eb
Step 2/16 : RUN set -ex;   apt-get update;   apt-get -y install libsnappy1v5 gettext-base;   rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> b747d5ffaeed
Step 3/16 : ENV GOSU_VERSION 1.11
 ---> Using cache
 ---> d1b0da5ae633
Step 4/16 : RUN set -ex;   wget -nv -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)";   wget -nv -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc";   export GNUPGHOME="$(mktemp -d)";   for server in ha.pool.sks-keyservers.net $(shuf -e                           hkp://p80.pool.sks-keyservers.net:80                           keyserver.ubuntu.com                           hkp://keyserver.ubuntu.com:80                           pgp.mit.edu) ; do       gpg --batch --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || : ;   done &&   gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;   gpgconf --kill all;   rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc;   chmod +x /usr/local/bin/gosu;   gosu nobody true
 ---> Using cache
 ---> 1edf262c7d6c
Step 5/16 : ENV FLINK_VERSION=1.10.0     SCALA_VERSION=2.11     GPG_KEY=BB137807CEFBE7DD2616556710B12A1F89C115E8
 ---> Using cache
 ---> ec957d818778
Step 6/16 : ENV FLINK_HOME=/opt/flink
 ---> Using cache
 ---> 01560a65b1ac
Step 7/16 : ENV PATH=$FLINK_HOME/bin:$PATH
 ---> Using cache
 ---> b56363e71fa3
Step 8/16 : RUN groupadd --system --gid=9999 flink &&     useradd --system --home-dir $FLINK_HOME --uid=9999 --gid=flink flink
 ---> Using cache
 ---> 6ce19acdaf69
Step 9/16 : WORKDIR $FLINK_HOME
 ---> Using cache
 ---> 813bdfb36942
Step 10/16 : ENV FLINK_URL_FILE_PATH=flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-scala_${SCALA_VERSION}.tgz
 ---> Using cache
 ---> fbf8c980a6a7
Step 11/16 : ENV FLINK_TGZ_URL=https://www.apache.org/dyn/closer.cgi?action=download&filename=${FLINK_URL_FILE_PATH}     FLINK_ASC_URL=https://www.apache.org/dist/${FLINK_URL_FILE_PATH}.asc
 ---> Using cache
 ---> f5af480415c4
Step 12/16 : RUN set -ex;   wget -nv -O flink.tgz "$FLINK_TGZ_URL";   wget -nv -O flink.tgz.asc "$FLINK_ASC_URL";     export GNUPGHOME="$(mktemp -d)";   for server in ha.pool.sks-keyservers.net $(shuf -e                           hkp://p80.pool.sks-keyservers.net:80                           keyserver.ubuntu.com                           hkp://keyserver.ubuntu.com:80                           pgp.mit.edu) ; do       gpg --batch --keyserver "$server" --recv-keys "$GPG_KEY" && break || : ;   done &&   gpg --batch --verify flink.tgz.asc flink.tgz;   gpgconf --kill all;   rm -rf "$GNUPGHOME" flink.tgz.asc;     tar -xf flink.tgz --strip-components=1;   rm flink.tgz;     chown -R flink:flink .;
 ---> Running in 155870bc22d6
+ wget -nv -O flink.tgz https://www.apache.org/dyn/closer.cgi?action=download&filename=flink/flink-1.10.0/flink-1.10.0-bin-scala_2.11.tgz
2020-02-12 02:42:11 URL:http://mirror.bit.edu.cn/apache/flink/flink-1.10.0/flink-1.10.0-bin-scala_2.11.tgz [288915095/288915095] -> "flink.tgz" [1]
+ wget -nv -O flink.tgz.asc https://www.apache.org/dist/flink/flink-1.10.0/flink-1.10.0-bin-scala_2.11.tgz.asc
2020-02-12 02:42:25 URL:https://www.apache.org/dist/flink/flink-1.10.0/flink-1.10.0-bin-scala_2.11.tgz.asc [833/833] -> "flink.tgz.asc" [1]
+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.12u4sj26mU
+ shuf -e hkp://p80.pool.sks-keyservers.net:80 keyserver.ubuntu.com hkp://keyserver.ubuntu.com:80 pgp.mit.edu
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys BB137807CEFBE7DD2616556710B12A1F89C115E8
gpg: keybox '/tmp/tmp.12u4sj26mU/pubring.kbx' created
gpg: /tmp/tmp.12u4sj26mU/trustdb.gpg: trustdb created
gpg: key 10B12A1F89C115E8: public key "Gary Yao <gary@apache.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
+ break
+ gpg --batch --verify flink.tgz.asc flink.tgz
gpg: Signature made Fri Feb  7 18:55:20 2020 UTC
gpg:                using RSA key BB137807CEFBE7DD2616556710B12A1F89C115E8
gpg: Good signature from "Gary Yao <gary@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BB13 7807 CEFB E7DD 2616  5567 10B1 2A1F 89C1 15E8
+ gpgconf --kill all
+ rm -rf /tmp/tmp.12u4sj26mU flink.tgz.asc
+ tar -xf flink.tgz --strip-components=1
+ rm flink.tgz
+ chown -R flink:flink .
Removing intermediate container 155870bc22d6
 ---> 3d5a7f650fb1
Step 13/16 : COPY docker-entrypoint.sh /
 ---> 2900cd1c82b6
Step 14/16 : ENTRYPOINT ["/docker-entrypoint.sh"]
 ---> Running in 4e80690496ae
Removing intermediate container 4e80690496ae
 ---> 186190c86dec
Step 15/16 : EXPOSE 6123 8081
 ---> Running in e5742a39add8
Removing intermediate container e5742a39add8
 ---> 53584a76fe5c
Step 16/16 : CMD ["help"]
 ---> Running in a573ad5189f1
Removing intermediate container a573ad5189f1
 ---> b0ad2cb192a9
Successfully built b0ad2cb192a9
Successfully tagged flink-1-10-pr-test:latest
```

@rmetzger could you also help check on your site? Will merge this PR is no issue observed. Thanks.

**Comment by rmetzger** [comment]
👍 
Building the image, starting jobmanager and taskamanger works --> good to merge.

The `help` command is a bit weird
```
➜  scala_2.11-debian git:(carp84-flink-15978) docker run flink-1-10-pr-test:latest help
Usage: docker-entrypoint.sh (jobmanager|taskmanager|help)
```

**Comment by carp84** [comment]
Thanks for the verification @rmetzger ! Will merge this one and open new issue to track the `help` command improvement.

**Comment by patricklucas** [comment]
@carp84 the build actually [fails](https://travis-ci.org/apache/flink-docker/builds/649355160) now because the 1.8 images are no longer available, and I forgot to add that step to the README.

Could you open another PR to remove the `1.8` directory, then update the PR on `official-images`?

I'll work on the README soon to make sure this is documented.

**Comment by carp84** [comment]
> @carp84 the build actually [fails](https://travis-ci.org/apache/flink-docker/builds/649355160) now because the 1.8 images are no longer available—I forgot to add the step to remove them to the README.
> 
> Could you open another PR to remove the `1.8` directory, then update the PR on `official-images`?
> 
> I'll work on the README soon to make sure this is documented.

Thanks for the follow up @patricklucas . So only images of the latest two versions will be kept, right? New PR #7 opened, will merge it if no other concerns. Thanks.

**Comment by patricklucas** [comment]
@carp84 the older images can still be downloaded, but will not be automatically rebuilt.

I opened #8 to update the README.md with this info.

**Pull request merged**
