### PR TITLE
[dev-1.12] Quote URL when downloading Flink using wget

### PR DESCRIPTION
**Pull request by rkhachatryan**

### CODE REVIEW

**Comment by rkhachatryan** [comment]
I see that escaping and expansion work in travis [logs](https://travis-ci.com/github/apache/flink-docker/builds/218942716):
```
Step 10/14 : RUN set -ex;   wget -nv -O flink.tgz ''"$FLINK_TGZ_URL"'';     if [ "$CHECK_GPG" = "true" ]; then     wget -nv -O flink.tgz.asc ''"$F
  ---> Running in e70e0194ce83
*+ wget -nv -O flink.tgz https://www.apache.org/dyn/closer.cgi?action=download&filename=flink/flink-1.12.1/flink-1.12.1-bin-scala_2.12.tgz
```

**Review by rmetzger — APPROVED** [review]
+1 to merge since it fixes the problem

Please change the commit message to "[hotfix]" before merging.

Can you also merge this to the "dev-master" branch?

**Comment by rkhachatryan** [comment]
Done, created #71 for master.
Merging once travis is geen.
Thanks for the review!

**Comment by zentol** [comment]
Shall we close this PR?

**Comment by rkhachatryan** [comment]
Yes, closing this PR.

**Pull request closed without merging**
